name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci || npm install
      - name: Start API & Wait
        run: |
          bash scripts/ci_start_api.sh
      - name: Run CI (lint+type+test+guards+perf)
        run: npm run ci:all
      - name: Upload API log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-log
          path: api.log
      - name: Policy – No Autofix
        run: node scripts/ci_no_autofix_check.mjs
      - name: Stop API
        if: always()
        run: bash scripts/ci_stop_api.sh
